#ifndef __C_CREATEREPOLIB_CONSTANTS_H__
#define __C_CREATEREPOLIB_CONSTANTS_H__

typedef enum {
    PKG_CHECKSUM_MD5,
    PKG_CHECKSUM_SHA1,
    PKG_CHECKSUM_SHA256
} ChecksumType;

#endif /* __C_CREATEREPOLIB_CONSTANTS_H__ */
