var annotated =
[
    [ "cr_BinaryData", "structcr___binary_data.html", "structcr___binary_data" ],
    [ "cr_ChangelogEntry", "structcr___changelog_entry.html", "structcr___changelog_entry" ],
    [ "cr_CompressionTask", "structcr___compression_task.html", "structcr___compression_task" ],
    [ "cr_ContentStat", "structcr___content_stat.html", "structcr___content_stat" ],
    [ "cr_DeltaPackage", "structcr___delta_package.html", "structcr___delta_package" ],
    [ "cr_DeltaTargetPackage", "structcr___delta_target_package.html", "structcr___delta_target_package" ],
    [ "cr_Dependency", "structcr___dependency.html", "structcr___dependency" ],
    [ "cr_DistroTag", "structcr___distro_tag.html", "structcr___distro_tag" ],
    [ "cr_EVR", "structcr___e_v_r.html", "structcr___e_v_r" ],
    [ "CR_FILE", "struct_c_r___f_i_l_e.html", "struct_c_r___f_i_l_e" ],
    [ "cr_HeaderRangeStruct", "structcr___header_range_struct.html", "structcr___header_range_struct" ],
    [ "cr_MetadataLocation", "structcr___metadata_location.html", "structcr___metadata_location" ],
    [ "cr_ModifyRepoTask", "structcr___modify_repo_task.html", "structcr___modify_repo_task" ],
    [ "cr_NEVR", "structcr___n_e_v_r.html", "structcr___n_e_v_r" ],
    [ "cr_NEVRA", "structcr___n_e_v_r_a.html", "structcr___n_e_v_r_a" ],
    [ "cr_Package", "structcr___package.html", "structcr___package" ],
    [ "cr_PackageFile", "structcr___package_file.html", "structcr___package_file" ],
    [ "cr_Repomd", "structcr___repomd.html", "structcr___repomd" ],
    [ "cr_RepomdRecord", "structcr___repomd_record.html", "structcr___repomd_record" ],
    [ "cr_RepomdRecordFillTask", "structcr___repomd_record_fill_task.html", "structcr___repomd_record_fill_task" ],
    [ "cr_SqliteDb", "structcr___sqlite_db.html", "structcr___sqlite_db" ],
    [ "cr_Statements", "unioncr___statements.html", "unioncr___statements" ],
    [ "cr_UpdateCollection", "structcr___update_collection.html", "structcr___update_collection" ],
    [ "cr_UpdateCollectionPackage", "structcr___update_collection_package.html", "structcr___update_collection_package" ],
    [ "cr_UpdateInfo", "structcr___update_info.html", "structcr___update_info" ],
    [ "cr_UpdateRecord", "structcr___update_record.html", "structcr___update_record" ],
    [ "cr_UpdateReference", "structcr___update_reference.html", "structcr___update_reference" ],
    [ "cr_Version", "structcr___version.html", "structcr___version" ],
    [ "cr_XmlFile", "structcr___xml_file.html", "structcr___xml_file" ],
    [ "cr_XmlStruct", "structcr___xml_struct.html", "structcr___xml_struct" ],
    [ "PoolTask", "struct_pool_task.html", "struct_pool_task" ],
    [ "UserData", "struct_user_data.html", "struct_user_data" ]
];