---
name: Python CI
on: [push, pull_request]

jobs:
  python-build:
    name: Python Build
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          sudo dnf -y install dnf-plugins-core
          sudo dnf -y builddep createrepo_c.spec

      - name: Compile and Install
        run: python3 -m pip install .

      - name: Test
        run: pytest --verbose --color=yes tests/python/tests/
