---
name: Python CI
on: pull_request

jobs:
  python-build:
    name: Python Build
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo dnf -y install dnf-plugins-core python3-pip
          sudo dnf -y builddep createrepo_c.spec
          pip install --upgrade pip
          pip install pytest

      - name: Compile and Install
        run: pip install .

      - name: Test
        run: pytest --verbose --color=yes tests/python/tests/
